### ISSUE TITLE
docker test报错

### ISSUE THREAD

**Issue by henry-tujia** [VergilGao/docker-mdc#50]
### 错误简介
已按照readme完成docker部署，进行测试

### 日志
````bash
root@openmediavault:/srv/dev-disk-by-uuid-2ee14b13-898d-4375-9a5f-6309fcd3ca27/resources# docker run --rm --name mdc_test -it -v ${PWD}/test:/data -e PUID=$(stat -c %u test) -e PGID=$(stat -c %g test) vergilgao/mdc
Setup Timezone to Asia/Shanghai
Checking if UID: 0 matches user
usermod: UID '0' already exists
Checking if GID: 0 matches user
Setting umask to 000
Checking if config file exist
Starting...
[*]================= Movie Data Capture =================
[*]                        6.0.2
[*]======================================================
[*] - Linux-5.10.0-0.bpo.8-amd64-x86_64-with
[*] - x86_64 - Python-3.8.12
[*]======================================================
[*] - 严禁在墙内宣传本项目 -
[*]======================================================
[+]Start at 2022-03-23 20:23:00
[+]Load Config file '/config/mdc.ini'.
[+]Main Working mode ## 1: Scraping ## , multi_threading on, nfo_skip_days=30
Traceback (most recent call last):
  File "pathlib.py", line 1288, in mkdir
FileNotFoundError: [Errno 2] No such file or directory: '/config/.local/share/mdc'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pathlib.py", line 1288, in mkdir
FileNotFoundError: [Errno 2] No such file or directory: '/config/.local/share'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Movie_Data_Capture.py", line 618, in <module>
  File "Movie_Data_Capture.py", line 542, in main
  File "ADC_function.py", line 549, in parallel_download_files
  File "pathlib.py", line 1292, in mkdir
  File "pathlib.py", line 1292, in mkdir
  File "pathlib.py", line 1288, in mkdir
PermissionError: [Errno 13] Permission denied: '/config/.local'
[18] Failed to execute script 'Movie_Data_Capture' due to unhandled exception!```

**Comment by VergilGao** [comment]
-e PUID=$(stat -c %u test) -e PGID=$(stat -c %g test)
这里的test替换成你的user名和group名

**Comment by henry-tujia** [comment]
> 稍等我测试一下
> 
> 因为逻辑特殊性，目前版本不支持 root 用户

ok，使用特定UID就可以了

**Comment by VergilGao** [comment]
已经更新，现在使用root用户应该也能正常运行了。
虽然不推荐。
